# Generated by Django 2.2.3 on 2019-08-27 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twogames',
            name='image',
            field=models.ImageField(default='account.png', upload_to='two_games_pics'),
        ),
        migrations.CreateModel(
            name='PomodoroGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='account.png', upload_to='pomodoro_pics')),
                ('atBats', models.IntegerField(default=0)),
                ('avg', models.IntegerField(default=0)),
                ('doubles', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('homeRuns', models.IntegerField(default=0)),
                ('lob', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('rbi', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('singles', models.IntegerField(default=0)),
                ('slg', models.IntegerField(default=0)),
                ('triples', models.IntegerField(default=0)),
                ('result', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('home', models.IntegerField(default=0)),
                ('away', models.IntegerField(default=0)),
                ('risk', models.IntegerField(default=0)),
                ('safe', models.IntegerField(default=0)),
                ('grandSlam', models.IntegerField(default=0)),
                ('off', models.IntegerField(default=0)),
                ('stop', models.IntegerField(default=0)),
                ('level', models.CharField(blank=True, default='Rookie', max_length=20, null=True)),
                ('final', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
