# Generated by Django 2.2.3 on 2019-09-06 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20190827_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PomodoroGame',
        ),
    ]
