# Generated by Django 2.2.3 on 2019-08-15 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test100React',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('image', models.ImageField(default='account.png', upload_to='test100react_pics')),
                ('atBats', models.IntegerField(default=0)),
                ('avg', models.IntegerField(default=0)),
                ('doubles', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('homeRuns', models.IntegerField(default=0)),
                ('lob', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('rbi', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('singles', models.IntegerField(default=0)),
                ('slg', models.IntegerField(default=0)),
                ('triples', models.IntegerField(default=0)),
                ('result', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('home', models.IntegerField(default=0)),
                ('away', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
