# Generated by Django 2.2.3 on 2019-08-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test100react', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test100react',
            name='risk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test100react',
            name='safe',
            field=models.IntegerField(default=0),
        ),
    ]
