# Generated by Django 2.2.3 on 2019-08-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test100react', '0002_auto_20190819_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='test100react',
            name='grandSlam',
            field=models.IntegerField(default=0),
        ),
    ]
