# Generated by Django 2.2.3 on 2019-08-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test100react', '0003_test100react_grandslam'),
    ]

    operations = [
        migrations.AddField(
            model_name='test100react',
            name='off',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test100react',
            name='stop',
            field=models.IntegerField(default=0),
        ),
    ]
