# Generated by Django 2.2.3 on 2019-08-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test100react', '0004_auto_20190819_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test100react',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
