# Generated by Django 2.2.3 on 2019-08-27 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(default=1, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('player_eight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_eight', to=settings.AUTH_USER_MODEL)),
                ('player_eleven', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_elven', to=settings.AUTH_USER_MODEL)),
                ('player_fifteen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_fifteen', to=settings.AUTH_USER_MODEL)),
                ('player_five', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_five', to=settings.AUTH_USER_MODEL)),
                ('player_four', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_four', to=settings.AUTH_USER_MODEL)),
                ('player_fourteen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_fourteen', to=settings.AUTH_USER_MODEL)),
                ('player_nine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_nine', to=settings.AUTH_USER_MODEL)),
                ('player_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_one', to=settings.AUTH_USER_MODEL)),
                ('player_seven', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_seven', to=settings.AUTH_USER_MODEL)),
                ('player_six', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_six', to=settings.AUTH_USER_MODEL)),
                ('player_sixteen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_sixteen', to=settings.AUTH_USER_MODEL)),
                ('player_ten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_ten', to=settings.AUTH_USER_MODEL)),
                ('player_thirteen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_thirteen', to=settings.AUTH_USER_MODEL)),
                ('player_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_three', to=settings.AUTH_USER_MODEL)),
                ('player_twelve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_twelve', to=settings.AUTH_USER_MODEL)),
                ('player_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_two', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
