# Generated by Django 2.2.3 on 2019-07-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20190730_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
