# Generated by Django 2.2.3 on 2019-09-16 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0002_fourpomodoro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='account.png', upload_to='pomodoro_pics')),
                ('atBats', models.IntegerField(default=0)),
                ('avg', models.IntegerField(default=0)),
                ('doubles', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('homeRuns', models.IntegerField(default=0)),
                ('lob', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('rbi', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('singles', models.IntegerField(default=0)),
                ('slg', models.IntegerField(default=0)),
                ('triples', models.IntegerField(default=0)),
                ('result', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('home', models.IntegerField(default=0)),
                ('away', models.IntegerField(default=0)),
                ('risk', models.IntegerField(default=0)),
                ('safe', models.IntegerField(default=0)),
                ('grandSlam', models.IntegerField(default=0)),
                ('off', models.IntegerField(default=0)),
                ('stop', models.IntegerField(default=0)),
                ('level', models.CharField(blank=True, default='Rookie', max_length=20, null=True)),
                ('final', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=250)),
                ('task_one', models.CharField(max_length=250)),
                ('task_two', models.CharField(max_length=250)),
                ('task_three', models.CharField(max_length=250)),
                ('task_four', models.CharField(max_length=250)),
                ('work_duration', models.IntegerField(default=0)),
                ('break_duration', models.IntegerField(default=0)),
                ('workTotal', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('breakTotal', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('donation', models.IntegerField(default=0)),
                ('firstHome', models.IntegerField(default=0)),
                ('firstPoints', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('four', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.FourPomodoro')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
