# Generated by Django 2.2.3 on 2019-10-31 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(default='100react.png', upload_to='decks_pics')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('screenshot1', models.ImageField(upload_to='decks_screenshots')),
                ('screenshot2', models.ImageField(upload_to='decks_screenshots')),
                ('screenshot3', models.ImageField(upload_to='decks_screenshots')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
