# Generated by Django 2.2.3 on 2019-10-31 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='screenshot1',
            new_name='screenshoot1',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='screenshot2',
            new_name='screenshoot2',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='screenshot3',
            new_name='screenshoot3',
        ),
    ]
