# Generated by Django 2.2.3 on 2019-10-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('game_type', models.CharField(choices=[('1', 'Focus'), ('2', 'Memory'), ('3', 'Reaction Time')], max_length=25)),
                ('average_score', models.IntegerField(default=0)),
                ('win_rate', models.IntegerField(default=0)),
            ],
        ),
    ]
